### ISSUE TITLE
Unable to locate install json

### ISSUE THREAD

**Issue by david01228** [League-of-Foundry-Developers/fvtt-advanced-macros#32]
Trying to install the module for the first time into a new install of foundry, and I cannot find where the install json file is located.

**Comment by mclemente** [comment]
Sorry about that. Try it again, the issue should be fixed now.

**Comment by david01228** [comment]
Nope, foundry still cannot find it. can you put in the direct link? (i had to do that with another module as well, but they had it on their front page)

**Comment by mclemente** [comment]
https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/releases/download/v1.15/module.json
